import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Script from 'next/script';
import '@repo/ui/globals.css';
import Navbar from './components/navbar';
import { AuthProvider } from './components/auth-provider';
import { QueryProvider } from './providers/query-provider';
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} h-full w-full `}>
        <Script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="bee06ba3-49c5-4482-ac36-23b77c17a0f7"
        />
        <QueryProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Toaster />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
