import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Sign in | short-ly',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col items-center justify-center min-h-[calc(100vh-4rem)] w-full px-4 py-12">
      <div className="w-full max-w-md">{children}</div>
    </div>
  );
}
