import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Sign in | E-kart',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="flex flex-col items-center justify-center h-full w-full px-4">{children}</div>;
}
